default_data: data/zh_CN.yaml
backup_dir: data/backup
module_dir: modules
custom_dir: custom_tabs
module_priority:
  - add_tag.py
  - edit_color.py
module_ignore:
  - __init__.py
  - homepage.py
color_list:
  purple: rgba(140, 82, 255, 0.4)
  pink: rgba(255, 132, 208, 0.4)
  blue: rgba(24, 158, 243, 0.4)
  yellow: rgba(255, 169, 2, 0.4)
  green: rgba(0, 163, 80, 0.4)
  crimson: rgba(254, 49, 203, 0.4)
  brown: rgba(255, 123, 2, 0.4)
